### ISSUE TITLE
Unable to create pin

### ISSUE THREAD

**Issue by carolhng** [bstoilov/py3-pinterest#111]
I downloaded the latest pinterest bot (with web driver) and run a simple test with headless chrome.
The browser pop out and I was able to login then chrome closed by itself with below message:

DevTools listening on ws://127.0.0.1:61609/devtools/browser/e1ff2acb-5dc4-477f-b4d6-bffc9e7b020c
[18020:15976:1223/212633.301:ERROR:device_event_log_impl.cc(211)] [21:26:33.301] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

The script still continued to proceed to pinterest.pin() but not able to pin.

Traceback (most recent call last):
  File "C:\xampp\htdocs\py3pin\db.py", line 69, in <module>
    print(pinterest.pin(board_id=param['boardId'], image_url=image, description=keywords,title=title, link=blogUrl))
  File "C:\Users\php8legs\AppData\Local\Programs\Python\Python39\lib\site-packages\py3pin\Pinterest.py", line 440, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data)
  File "C:\Users\php8legs\AppData\Local\Programs\Python\Python39\lib\site-packages\py3pin\Pinterest.py", line 115, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "C:\Users\php8legs\AppData\Local\Programs\Python\Python39\lib\site-packages\py3pin\Pinterest.py", line 107, in request
    response.raise_for_status()
  File "C:\Users\php8legs\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.pinterest.com/resource/PinResource/create/

Is the bad request related to error above or different problems?

Thanks.

**Comment by carolhng** [comment]
For webdriver's USB error, I am not able to find solutions from google search. 
pinterest.login(headless=False) will cause browser to close by itself. But this error is not affecting py3pin.

For second error, it was because I use pinterest.pin() instead of pinterest.upload_pin() for local image.

Now I can create pins already. 

Thank you for the great script!
