### ISSUE TITLE
Facing problem with pinning Image 

### ISSUE THREAD

**Issue by ibikhan1234** [bstoilov/py3-pinterest#148]
I am successfully logged in.
Got Board Ids from my profile.

but still having issues like below at upload_pin function.

Successfully logged in with account abc@gmail.com
Traceback (most recent call last):
  File "c:/Users/useruser/Documents/pyqt5-test/py3pin/main.py", line 20, in <module>
    pinterest.upload_pin(board_id='789889359553000095', description='this is auto pin', title='a bot did this',image_file='1777.jpg', link='https://www.inspiringnorah.com')
  File "F:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\py3pin\Pinterest.py", line 460, in upload_pin       
    section_id=section_id)
  File "F:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\py3pin\Pinterest.py", line 452, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data)
  File "F:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\py3pin\Pinterest.py", line 115, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "F:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\py3pin\Pinterest.py", line 107, in request
    response.raise_for_status()
  File "F:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\requests\models.py", line 943, in raise_for_status  
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/

**Comment by umar-farooq-khan** [comment]
Same issue. :((((((((((( Yesterday everything worked. :( after now not working after I lost my code yesterday.

**Comment by umar-farooq-khan** [comment]
oh no no, it works, the error was in email I didnt wrote @gmail.com

**Comment by anuroop18** [comment]
Is this code really working for you? @umar-farooq-khan 
Because i am getting the same error but my email is correct. I don't know what is the problem.

**Comment by umar-farooq-khan** [comment]
yes it works. but only sometimes, It started giving error. but again there is always a problem with our code.
I found one reason, 
one is first letter must be capital and most importantly, lower the number of characters of title and desc. start with very lower and try the code. and start increasing it. Too long title or desc will not work.

**Comment by ibikhan1234** [comment]
> importantly

do you have skype or facebook? lets resove the issue together.

**Comment by Nephirelle** [comment]
Hey guys, sounds like an interesting investigation. I made some Wireshark recordings some weeks ago while uploading pins with images via website and compared it to what is sent via py3pin. It looked quite different. The website uses HTTP2, the headers are not the same and images are uploaded as a stream. Since HTTP2 requires encrypted communication, I thought this was the reason for the "unauthorized" error. So I thought it would never work without changing the communication layer completely. Actually, I wonder how it can work by changing some text content?

Attached, you find my recordings.

![py3pin_upload](https://user-images.githubusercontent.com/39213466/126755912-261b26ba-96ec-48cd-b369-d525431f5e19.png)
![webpage_upload_1](https://user-images.githubusercontent.com/39213466/126755914-59ddceff-ad3c-4be9-b443-d3fd01fb4cc9.png)
![webpage_upload_2](https://user-images.githubusercontent.com/39213466/126755918-c6f4c20b-9635-42ab-a2b3-35fc6e281e74.png)

**Comment by bstoilov** [comment]
That is some really advanced investigation, I usually just inspect the network tab and repeat the requests in python. Everything seems to be working locally on my machine, looks like for some reason the login fails. Try deleting the cred folder, do login and see if it get populated again

**Comment by Carnagency** [comment]
I have tried a lot of the things that were discussed in all the different conversations of the repositery.

I was really hopeless and I found that it was simply due to me living in a non-english country so I just had to change the settings of my pinterest account and put US in country and american english in language.

Check this link out :

https://docs.contentstudio.io/article/497-pinterest-post-failed-to-publish#:~:text=Authorization%20Problem%3A%20If%20you%20are,the%20account%20to%20the%20English.

Hope this will help some fellow coders !

**Comment by bstoilov** [comment]
fixed verfied in https://github.com/bstoilov/py3-pinterest/pull/222
