### ISSUE TITLE
Cannot create or upload pin

### ISSUE THREAD

**Issue by RedWideWeb** [bstoilov/py3-pinterest#152]
`pinterest.pin(
            board_id=board_id,
            image_url=image_url,
            description='description',
            link='linkkkkk',
            title='Pin pin'
        )`

Gives an error 404:

`Traceback (most recent call last):
  File "/Users/mikhail.savin/PycharmProjects/GPT-3/post_pinterest.py", line 86, in <module>
    pinterest.pin(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py3pin/Pinterest.py", line 441, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py3pin/Pinterest.py", line 115, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py3pin/Pinterest.py", line 107, in request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/`

Same when uploading an image. It actually upload successfully but cannot be pinned

**Comment by RedWideWeb** [comment]
First of all board_id needs to be string, not integer. After I fixed that (which could be implemented in the library) it gave 400 Error Bad request

That is because link needs to be real but I just put random junk there. Keep that in mind!
