### ISSUE TITLE
I can't upload a new pin to my board

### ISSUE THREAD

**Issue by Berseck20** [bstoilov/py3-pinterest#178]
CODE:
`userBoardID = userDict["id"]

    userBoardPinPath = "Test Image_064.jpg"

    pinterest.upload_pin(board_id=userBoardID, section_id="", image_file=userBoardPinPath, description="Test", title="Test", link="https://example.com")
`

ERROR:
`No credentials stored [Errno 2] No such file or directory: 'user_root\\testemail@gmail.com'

DevTools listening on ws://127.0.0.1:63927/devtools/browser/a433f320-b4cf-4bbc-b45c-29483c00ae1a
Failed to login 'WebDriver' object has no attribute 'find_element_by_id'
Successfully logged in with account testemail@gmail.com
Traceback (most recent call last):
  File "D:\Usuario\Desktop\PINTEREST-CPA\pinterest-testing-app\main.py", line 81, in <module>
    main()
  File "D:\Usuario\Desktop\PINTEREST-CPA\pinterest-testing-app\main.py", line 74, in main
    pinterest.upload_pin(board_id=userBoardID, section_id="", image_file=userBoardPinPath, description="test description", title="test title", link="https://example.com")
  File "D:\Usuario\Desktop\PINTEREST-CPA\pinterest-testing-app\venv\lib\site-packages\py3pin\Pinterest.py", line 600, in upload_pin
    image_url = self._upload_image(image_file=image_file).json()["image_url"]
  File "D:\Usuario\Desktop\PINTEREST-CPA\pinterest-testing-app\venv\lib\site-packages\py3pin\Pinterest.py", line 642, in _upload_image
    return self.post(url=UPLOAD_IMAGE, data=form_data, headers=headers)
  File "D:\Usuario\Desktop\PINTEREST-CPA\pinterest-testing-app\venv\lib\site-packages\py3pin\Pinterest.py", line 172, in post
    return self.request(
  File "D:\Usuario\Desktop\PINTEREST-CPA\pinterest-testing-app\venv\lib\site-packages\py3pin\Pinterest.py", line 164, in request
    response.raise_for_status()
  File "D:\Usuario\Desktop\PINTEREST-CPA\pinterest-testing-app\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.pinterest.com/upload-image/`

**using the "headless = False" opens a window with the pinterest login, apparently it is not writing in the fields "email" and "password" the respective data and still tells me:

failed login
succesfully logged in

the error may be because it does not write the selenium data in the fields?**

**Comment by michaelteey** [comment]
yo! just found that selenium has updated where "find_element_by_id" and "find_elments_by_xpath" does not work any longer, so you're not actually being logged in - you now have to use find_element("id", "path")

i had to chance the source code to get it to work - @bstoilov FYI if you haven't seen :)

**Comment by Berseck20** [comment]
Yes I saw it too and changed it, but it still doesn't log me in when I try the bot.

**Comment by bstoilov** [comment]
verified/fixed in https://github.com/bstoilov/py3-pinterest/pull/222
