### ISSUE TITLE
404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/

### ISSUE THREAD

**Issue by inspiringnorah** [bstoilov/py3-pinterest#188]
After successful login message when i execute the following code 

```
currdir = os.path.dirname(__file__)
response  = pinterest.upload_pin(board_id='497577596238700583',
            image_file=currdir+'/aaa.jpg',
            description='This is th epin desc',
            title='This is the title',
            link='www.youtube.com')

print(response)
```

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/

### COMPLETE MESSAGE:

Successfully logged in with account ABC@emaill.com

Traceback (most recent call last):
  File ".\2023_script.py", line 21, in <module>
    link='www.youtube.com')
  File "G:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\py3pin\Pinterest.py", line 600, in upload_pin
    return self.pin(board_id=board_id, description=description, image_url=image_url, link=link, title=title, section_id=section_id,)
  File "G:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\py3pin\Pinterest.py", line 593, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data)
  File "G:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\py3pin\Pinterest.py", line 174, in post
    "POST", url=url, data=data, files=files, extra_headers=headers
  File "G:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\py3pin\Pinterest.py", line 165, in request
    response.raise_for_status()
  File "G:\NetBeansProjects\Instagram\instoo\Python37\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/

**Comment by Arpit980jai** [comment]
Facing the same issue is it resolved?

**Comment by bstoilov** [comment]
fixed in https://github.com/bstoilov/py3-pinterest/pull/222
