### ISSUE TITLE
Timeout value connect was <object object at 0x000001714FAC8660>, but it must be an int, float or None.

### ISSUE THREAD

**Issue by Arpit980jai** [bstoilov/py3-pinterest#202]
Please help me 
 when i have cloned then its all working fine but not working when i am trying to create by new project 
Hello i have created new project and after that as per the instruction i have installed py3-pinterest
 pip install py3-pinterest
 for which i have recived this response
  
  Response in terminal 
 ```
 Collecting py3-pinterest
  Using cached py3-pinterest-1.3.0.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from py3-pinterest) (2.31.0)
Requirement already satisfied: beautifulsoup4 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from py3-pinterest) (4.12.3)
Requirement already satisfied: requests-toolbelt in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from py3-pinterest) (1.0.0)
Requirement already satisfied: selenium in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from py3-pinterest) (3.141.0)
Collecting webdriver-manager (from py3-pinterest)
  Using cached webdriver_manager-4.0.1-py2.py3-none-any.whl (27 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from beautifulsoup4->py3-pinterest) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from requests->py3-pinterest) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from requests->py3-pinterest) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from requests->py3-pinterest) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from requests->py3-pinterest) (2022.12.7)
Collecting python-dotenv (from webdriver-manager->py3-pinterest)
  Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Requirement already satisfied: packaging in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from webdriver-manager->py3-pinterest) (23.1)
Building wheels for collected packages: py3-pinterest
  Building wheel for py3-pinterest (setup.py) ... done
  Created wheel for py3-pinterest: filename=py3_pinterest-1.3.0-py3-none-any.whl size=15461 sha256=99044a8e18b96f3154dd910f36ca42b4218209088763e1c6725b86de7a61137f
  Stored in directory: c:\users\acer\appdata\local\pip\cache\wheels\a5\81\43\49d96ed15fd15197354fc2783039c6865da3055f74e18fc15e
Successfully built py3-pinterest
Installing collected packages: python-dotenv, webdriver-manager, py3-pinterest
Successfully installed py3-pinterest-1.3.0 python-dotenv-1.0.1 webdriver-manager-4.0.1
```

After doing this  i have written the code

```
from py3pin.Pinterest import Pinterest

pinterest = Pinterest(email='aisha900kapoor@gmail.com',
                      password='Aisha@123',
                      username='aisha980kapoor',
                      cred_root='cred_root')
pinterest.login()

```
but it gave me error
```
`No credentials stored [Errno 2] No such file or directory: 'cred_root\\aisha980kapoor@gmail.com'
Traceback (most recent call last):
  File "C:\Users\acer\PycharmProjects\pinterestuploader3\main.py", line 7, in <module>
    pinterest.login()
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\py3pin\Pinterest.py", line 198, in login
    driver = webdriver.Chrome(
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\poolmanager.py", line 433, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\poolmanager.py", line 304, in connection_from_host
    return self.connection_from_context(request_context)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\poolmanager.py", line 329, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\poolmanager.py", line 352, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\poolmanager.py", line 266, in _new_pool
    return pool_cls(host, port, **request_context)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 196, in __init__
    timeout = Timeout.from_float(timeout)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\timeout.py", line 152, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x000001714FAC8660>, but it must be an int, float or None.
`
```

**Comment by bstoilov** [comment]
The error was caused by selenium==3.141.0 being incompatible with urllib3>=2.x.

fixed in https://github.com/bstoilov/py3-pinterest/pull/222
