### ISSUE TITLE
404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/

### ISSUE THREAD

**Issue by imdadadenangua** [bstoilov/py3-pinterest#207]
`pin_response = pinterest.upload_pin(board_id='',
                                    image_file='2.png',
                                    description='TESTING PIN FUNCTIONALITY WITH ID FETCHING',
                                    title='Foobar Barfood',
                                    section_id=None,
                                    link='')

response_data = json.loads(pin_response.content)
print(response_data)`

Traceback (most recent call last):
  File "D:\phpstudy_pro\WWW\py\postpin\01.py", line 27, in <module>
    pin_response = pinterest.upload_pin(board_id='',
  File "D:\phpstudy_pro\WWW\py\postpin\venv\lib\site-packages\py3pin\Pinterest.py", line 636, in upload_pin
    return self.pin(
  File "D:\phpstudy_pro\WWW\py\postpin\venv\lib\site-packages\py3pin\Pinterest.py", line 627, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data)
  File "D:\phpstudy_pro\WWW\py\postpin\venv\lib\site-packages\py3pin\Pinterest.py", line 178, in post
    return self.request(
  File "D:\phpstudy_pro\WWW\py\postpin\venv\lib\site-packages\py3pin\Pinterest.py", line 170, in request
    response.raise_for_status()
  File "D:\phpstudy_pro\WWW\py\postpin\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/ApiResource/create/

**Comment by ponideal** [comment]
same_error

**Comment by hujiamin1997** [comment]
I have already solved the problem; the issue was that the title was too long.

**Comment by ponideal** [comment]
> I have already solved the problem; the issue was that the title was too long.

my title 1 word :)

**Comment by ponideal** [comment]
> I have already solved the problem; the issue was that the title was too long.

u use pin or upload pin ?

**Comment by bstoilov** [comment]
verified/fixed in https://github.com/bstoilov/py3-pinterest/issues/213
