### ISSUE TITLE
pinterest.board_feed() returns 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by memesanddremes** [bstoilov/py3-pinterest#214]
Hello, I'm getting an error when trying to use one function in particular: board_feed(). I'm able to log in and get a list of my boards, but as soon as I try to list the pins in a board I get this error:
```
Traceback (most recent call last):
  File "E:/other_files/scripts/python/PinterestBoardSync/main.py", line 10, in <module>
    print(pinterest.board_feed(board_id="818177525994281131", page_size=25))
  File "E:\other_files\scripts\python\PinterestBoardSync\venv\lib\site-packages\py3pin\Pinterest.py", line 1108, in board_feed
    response = self.get(url=url).json()
  File "E:\other_files\scripts\python\PinterestBoardSync\venv\lib\site-packages\py3pin\Pinterest.py", line 172, in get
    return self.request("GET", url=url)
  File "E:\other_files\scripts\python\PinterestBoardSync\venv\lib\site-packages\py3pin\Pinterest.py", line 167, in request
    response.raise_for_status()
  File "E:\other_files\scripts\python\PinterestBoardSync\venv\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.pinterest.com/resource/BoardFeedResource/get/?source_url=%2F&data=%7B%22options%22%3A%20%7B%22isPrefetch%22%3A%20false%2C%20%22board_id%22%3A%20%22818177525994281131%22%2C%20%22field_set_key%22%3A%20%22partner_react_grid_pin%22%2C%20%22filter_section_pins%22%3A%20true%2C%20%22layout%22%3A%20%22default%22%2C%20%22page_size%22%3A%2025%2C%20%22redux_normalize_feed%22%3A%20true%2C%20%22bookmarks%22%3A%20%5Bnull%5D%7D%2C%20%22context%22%3A%20null%7D&_=1733881843739
```
My code is as follows:
```py
from py3pin.Pinterest import Pinterest


pinterest = Pinterest(email='',
                    password='',
                    username='',
                    cred_root='cred_root')

pinterest.login()
print(pinterest.board_feed(board_id="818177525994281131", page_size=25))
pinterest.logout()
```
The board is a public board with one image to test, I've tripled check the board id so I'm not sure if I made a mistake or there's an issue with the repo. Any help would be appreciated, thanks.

**Comment by EssadikElmangoug** [comment]
I’m encountering the same error! The issue seems to be with the URL generated using `req_builder` the response is `Invalid Resource Request`. I suspect Pinterest has updated and blocked the board pins fetcher API.

**Comment by Nviard** [comment]
I didn't have time to test it yet, but I found  [this issue](https://github.com/mikf/gallery-dl/issues/6513) on another project that could help to fix your issue.

**Comment by memesanddremes** [comment]
Just tested it and it works for me to. Thank you 👍
