### ISSUE TITLE
pinterest.pin() problem 

### ISSUE THREAD

**Issue by halibilen** [bstoilov/py3-pinterest#34]
my pin parameters  like this : 
pinterest.pin(board_id=627689404223348588, image_url='https://i.pinimg.com/564x/7b/ca/94/7bca948f5a5ca23a5189cfab47c157c6.jpg', description='example description', title='example title')

but i receive an error : 

---------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Fatma\Desktop\ali.py", line 20, in <module>
    pinterest.pin(board_id=627689404223348588, image_url='https://i.pinimg.com/564x/7b/ca/94/7bca948f5a5ca23a5189cfab47c157c6.jpg', description='description', title='title is here')
  File "C:\python35\lib\site-packages\py3pin\Pinterest.py", line 270, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data)
  File "C:\python35\lib\site-packages\py3pin\Pinterest.py", line 106, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "C:\python35\lib\site-packages\py3pin\Pinterest.py", line 98, in request
    response.raise_for_status()
  File "C:\python35\lib\site-packages\requests\models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/
>>> 

Can you help me ??

**Comment by bstoilov** [comment]
can you try passing the board id as string?

**Comment by halibilen** [comment]
I tried but error was same : 
=================== RESTART: C:\Users\Fatma\Desktop\ali.py ===================
Traceback (most recent call last):
  File "C:\Users\Fatma\Desktop\ali.py", line 23, in <module>
    pinterest.pin(board_id='627689404223348588', image_url='https://i.pinimg.com/564x/7b/ca/94/7bca948f5a5ca23a5189cfab47c157c6.jpg', description='example description', title='example title')
  File "C:\python35\lib\site-packages\py3pin\Pinterest.py", line 270, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data)
  File "C:\python35\lib\site-packages\py3pin\Pinterest.py", line 106, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "C:\python35\lib\site-packages\py3pin\Pinterest.py", line 98, in request
    response.raise_for_status()
  File "C:\python35\lib\site-packages\requests\models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/
>>>

**Comment by bstoilov** [comment]
Make sure the board id is correct.Everything is working fine wit my profile, the boardId should be one of your board, or board you have right to pin to.

Other than that your request looks fine.

Also make sure you are using the latest version

**Comment by bstoilov** [comment]
Hello are you still facing issues with this?

**Comment by Aarushi-Ign** [comment]
Hello, I am facing the same issue. The board ID is correct.
Traceback (most recent call last):
  File "pinit.py", line 42, in <module>
    pinterest.pin(board_id='771874892324362501', section_id=None, image_url=image_file, description=description, title=title, link=link)
  File "/usr/local/lib/python3.5/dist-packages/py3pin/Pinterest.py", line 270, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data)
  File "/usr/local/lib/python3.5/dist-packages/py3pin/Pinterest.py", line 106, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/py3pin/Pinterest.py", line 98, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.pinterest.com/resource/PinResource/create/
