### ISSUE TITLE
Repin doesn't work 401 Client Error

### ISSUE THREAD

**Issue by timmoh** [bstoilov/py3-pinterest#69]
Repin doesn't work. Unauthorized for url: https://www.pinterest.com/resource/RepinResource/create/

```
pinterest = Pinterest(email='xxxx@xxxx.zz',
                      password='xxxx',
                      username='xxxxxxxxx',
                      cred_root='cred_root')
logged_in = pinterest.login()
searchquery='diy'
board_id = 764275067953234231965
print("Search for " + searchquery)
search_batch = pinterest.search(scope='pins', query=searchquery)
fristPin = search_batch[0]
pin_id = fristPin['id']
print(fristPin)
print("Repinning pin from " + fristPin['domain'] + "(" + str(pin_id) + ") to Board:" + str(board_id))
pinterest.repin(board_id=board_id, pin_id=pin_id)
```

Errormessage:
```
Traceback (most recent call last):
  File "....python/py3-pinterest/repin.py", line 37, in <module>
    pinterest.repin(board_id=board_id, pin_id=pin_id)
  File "....python/py3-pinterest/venv/lib/python3.7/site-packages/py3pin/Pinterest.py", line 433, in repin
    return self.post(url=REPIN_RESOURCE_CREATE, data=data)
  File "....python/py3-pinterest/venv/lib/python3.7/site-packages/py3pin/Pinterest.py", line 111, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "....python/py3-pinterest/venv/lib/python3.7/site-packages/py3pin/Pinterest.py", line 103, in request
    response.raise_for_status()
  File "....python/py3-pinterest/venv/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.pinterest.com/resource/RepinResource/create/

Process finished with exit code 1
```

**Comment by timmoh** [comment]
ahhh I got it. board_id and pin_id should be a string.
Perghaps type hinting would be good in the function @bstoilov
