### ISSUE TITLE
401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by tasiotas** [bstoilov/py3-pinterest#88]
Hi,

I'm having trouble with pinning to board on Pinterest.
Seems like I can successfully login, retrieve my boards, but pinning throws error.
Any clue what am I doing wrong here?

Thank you!

```
pinterest = Pinterest(email='xxx',
                          password='xxx',
                          username='xxx',
                          cred_root='cred_root')

login = pinterest.login()
print("login: %s" % (login))

boards = pinterest.boards()
for i in boards:
    print(i['name'])
    print(i['id'])


pin_response = pinterest.upload_pin(board_id='693835955031482033',
                                    image_file='thumb.jpg',
                                    description='TESTING PIN FUNCTIONALITY WITH ID FETCHING',
                                    title='Foobar Barfood',
                                    section_id=None,
                                    link='')`
```

Output:

```
login: <Response [200]>
My Board
693835955031482033
Traceback (most recent call last):
  File ".../postPinterest.py", line 33, in <module>
    postPinterest()
  File ".../postPinterest.py", line 25, in postPinterest
    pin_response = pinterest.upload_pin(board_id='693835955031482033',
  File "...\py3pin\Pinterest.py", line 414, in upload_pin     
    return self.pin(board_id=board_id, description=description, image_url=image_url, link=link, title=title,
  File "...\py3pin\Pinterest.py", line 407, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data)
  File "...\py3pin\Pinterest.py", line 111, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "...\py3pin\Pinterest.py", line 103, in request        
    response.raise_for_status()
  File "...\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.pinterest.com/resource/PinResource/create/
```

**Comment by tasiotas** [comment]
There is one odd thing I noticed.
On my account I have Business account as well. It looks like its nested or related to my personal account.

When I create board with `pinterest.create_board('Design', 'Design')`, board gets created in my personal account.
When I retrieve boards with `pinterest.boards()`, I get a list of my business account boards.

I am bit confused, because I have only one credentials for both accounts. Have anyone used py3pin with Business account?

**Comment by bstoilov** [comment]
Are you getting only the business boards or all boards? I never tested with business accounts

**Comment by tasiotas** [comment]
Only business boards. I understand that your module doesnt work with Business accounts. No worries, I already switched to Selenium for my needs.

Thanks!
